### ISSUE TITLE
React Native support?

### ISSUE THREAD

**Issue by aksonov** [calmm-js/kefir.react.html#1]
Any plans for it?

**Comment by polytypic** [comment]
Related: https://gitter.im/calmm-js/chat?at=57135dc72c9711166432a0a0

There are no plans in the sense that anyone would be working on it and I'm not currently working on a mobile project.  However, it shouldn't be very difficult to implement a React Native version of `kefir.react.html`.  If someone is interested in trying it I'd be happy to help.

**Comment by polytypic** [comment]
[Redirect](https://github.com/calmm-js/kefir.react.native)
